version: 0.0.{build}
os: MinGW
install:
  - set QTDIR=C:\Qt\5.4\msvc2013_opengl
  - set PATH=%PATH%;%QTDIR%\bin
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86
build_script:
  - git submodule update --init --recursive
  - cd qt-property-browser
  - configure.bat
  - cd ..\
  - qmake Cadencii.pro
  - nmake
  - mkdir artifacts\Cadencii-%APPVEYOR_BUILD_VERSION%
  - copy /y bin\release\Cadencii.exe artifacts\Cadencii-%APPVEYOR_BUILD_VERSION%
  - call %QTDIR%\bin\windeployqt.exe artifacts\Cadencii-%APPVEYOR_BUILD_VERSION%\Cadencii.exe
artifacts:
  - path: artifacts\Cadencii-%APPVEYOR_BUILD_VERSION%
    type: zip
