######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 26 02:59:52 2012
######################################################################

QT += testlib widgets
TEMPLATE = app
TARGET = ui-test
DEPENDPATH += .
INCLUDEPATH += . ../ /usr/local/include ../vsq/include

include(../qt-property-browser/src/qtpropertybrowser.pri)
include(../cadencii_common.pri)

# Input
HEADERS += \
    Test.hpp \
    ConcreteTrackListViewStub.hpp \
    ConcretePropertyViewStub.hpp

SOURCES += \
    main.cpp \
    Test.cpp

DESTDIR = bin
OBJECTS_DIR = $$DESTDIR
MOC_DIR = $$DESTDIR
RCC_DIR = $$DESTDIR
UI_DIR = $$DESTDIR
